DROP TABLE IF EXISTS vehicle_type;

CREATE TABLE IF NOT EXISTS vehicle_type (
      id SERIAL PRIMARY KEY,
      type_name VARCHAR(100) NOT NULL UNIQUE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
